name: Build and Deploy VitePress Docs

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 初始化 package.json（如果不存在）
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: 安装依赖
        run: npm install

      - name: 生成 sidebar 配置文件
        run: node .github/scripts/generateSidebar.cjs

      - name: 构建网站
        run: npx vitepress build .

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
